version:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
  - 3.13
  - 3.14
  - 3.14
py_impl:
  - cpython
  - cpython
  - cpython
  - cp313
  - cp313t
  - cp314
  - cp314t
freethreading:
  - no
  - no
  - no
  - no
  - yes
  - no
  - yes
channel_sources:
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
  - conda-forge
cross_target_platform:
  - "linux-64"
  - "linux-ppc64le"
  - "linux-aarch64"
  - "osx-64"
  - "osx-arm64"
zip_keys:
  - - version
    - py_impl
    - channel_sources
    - freethreading
